- **simulation**: an imitation of a real-word process
- **trial**: one of the events that makes up a simulation

In [1]:
import numpy as np

In [42]:
flips = np.random.choice(['Heads', 'Tails'], size=1000)
(flips == 'Heads').mean()

0.482

In [ ]:
# how many heads do we get after flipping 2 coins?
# n trials = 2
# n simulations = 10,000

How to do simulation with python and numpy

1. Figure out a way to represent our data
1. Create a matrix of random data, rows = simulations, columns = trials
1. Apply an aggregate row-wise to get the results of each simulation
1. Apply a final aggreate to get our probability

> What's the probability I get 2 or more heads after flipping 3 coins?

In [54]:
# 1. represent our data -- 0 is tails, 1 is heads
# 2. create a matrix (nrows, ncols)

flips = np.random.choice([0, 1], size=(10_000, 3))
flips

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       ...,
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [55]:
# 3. Apply an aggregate row-wise to get the results of each simulation
simulation_results = flips.sum(axis=1)
simulation_results

array([2, 1, 2, ..., 1, 1, 0])

In [56]:
# 4. Apply a final aggregation to get the probability
(simulation_results >= 2).mean()

0.5025

In [109]:
np.random.seed(123) # for reproducibility
np.random.choice(['a', 'b', 'c'], size=25, p=[1/3, 1/3, 1/3])

array(['c', 'a', 'a', 'b', 'c', 'b', 'c', 'c', 'b', 'b', 'b', 'c', 'b',
       'a', 'b', 'c', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'b', 'c'],
      dtype='<U1')

In [110]:
np.random.seed(42)
np.random.uniform(size=100)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
       0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
       0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249,
       0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446,
       0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
       0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033,
       0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
       0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694,
       0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685

In [112]:
np.random.normal(3, 1, size=100)

array([2.70099265, 3.09176078, 1.01243109, 2.78032811, 3.35711257,
       4.47789404, 2.48172978, 2.1915064 , 2.49824296, 3.91540212,
       3.32875111, 2.4702398 , 3.51326743, 3.09707755, 3.96864499,
       2.29794691, 2.67233785, 2.60789185, 1.53648505, 3.29612028,
       3.26105527, 3.00511346, 2.76541287, 1.58462926, 2.57935468,
       2.65728548, 2.19772273, 2.83871429, 3.40405086, 4.8861859 ,
       3.17457781, 3.25755039, 2.92555408, 1.08122878, 2.97348612,
       3.06023021, 5.46324211, 2.80763904, 3.30154734, 2.96528823,
       1.83132196, 4.14282281, 3.75193303, 3.79103195, 2.09061255,
       4.40279431, 1.59814894, 3.58685709, 5.19045563, 2.00946367,
       2.43370227, 3.09965137, 2.49652435, 1.44933657, 3.06856297,
       1.93769629, 3.47359243, 2.08057577, 4.54993441, 2.21674671,
       2.67793848, 3.81351722, 1.76913568, 3.22745993, 4.30714275,
       1.39251677, 3.18463386, 3.25988279, 3.78182287, 1.76304929,
       1.67954339, 3.52194157, 3.29698467, 3.25049285, 3.34644

> You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).
> 
> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.
>
> Assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?

1. Calculate P(win)
1. Determine whether we should play

In [131]:
# 1. data representation, numbers 1-6 represent which side came up on a die
# 2. matrix of random numbers

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=(10_000, 3))
rolls

array([[4, 6, 1],
       [5, 1, 1],
       [6, 5, 4],
       ...,
       [3, 3, 3],
       [6, 3, 3],
       [4, 3, 6]])

In [132]:
#. 3. Aggregate row-wise to get the results of each simulation
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls

array([11,  7, 15, ...,  9, 12, 13])

In [133]:
p_win = (sum_of_rolls >= 12).mean()
p_win

0.3723

In [134]:
expected_winnings = p_win * 15
expected_winnings

5.5845